### ISSUE TITLE
Exception when extension registers service

### ISSUE THREAD

**Issue by JSilent** [amun-ai/hypha#726]
Hi,

An extension is defined and ready to call register_service. However exception pops up as below:
```
Traceback (most recent call last):
  File "/usr/local/lib/python3.12/site-packages/hypha_rpc/rpc.py", line 732, in register_service
    await manager.register_service(service_info)
hypha_rpc.rpc.RemoteException: RemoteError:Traceback (most recent call last):
             ^^^^^^^^^^^^
  File "/opt/conda/lib/python3.12/site-packages/hypha_rpc/utils/schema.py", line 401, in wrapper
    ret = await original_func(*new_args, **new_kwargs)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/hypha/core/workspace.py", line 1162, in register_service
    key = f"services:{service.config.visibility.value}|{service.type}:{service.id}@{service.app_id}"
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'str' object has no attribute 'value'
Exception: Traceback (most recent call last):
             ^^^^^^^^^^^^
  File "/opt/conda/lib/python3.12/site-packages/hypha_rpc/utils/schema.py", line 401, in wrapper
    ret = await original_func(*new_args, **new_kwargs)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/hypha/core/workspace.py", line 1162, in register_service
    key = f"services:{service.config.visibility.value}|{service.type}:{service.id}@{service.app_id}"
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'str' object has no attribute 'value'
```

Code:
```
    extension = {
        "_rintf": True,
        "id": "xxxxx-agent",
        "type": "xxxxx-chatbot-extension",
        "name": "xxxxxxxxxx",
        "description": description_str,
        "docs": docs_str,
        "get_schema": usecase.get_schema,
        "tools": usecase.tools,
        "config":
            {
                "visibility": "public",
                "run_in_executor": True
            },
        "info": usecase.info
    }
```

The python packages installed:
```
schema-agents>=0.1.53
hypha-rpc==0.20.41
hypha==0.20.41
requests
matplotlib
tqdm
aiofiles
langchain>=0.2.11
langchain-community==0.2.10
langchain-core==0.2.24
langchain-openai==0.1.19
rank-bm25==0.2.2
setuptools
python-dotenv==1.0.1
fastapi
websockets==13.1
```
```
dependencies = [
  "python-dotenv",
  "schema-agents>=0.1.53",
  "hypha-rpc==0.20.41",
  "requests",
  "matplotlib",
  "tqdm",
  "aiofiles",
  "langchain>=0.2.11",
  "pandas",
  "rank-bm25",
  "langchain-openai>=0.1.19",
  "langchain-core>=0.2.24",
  "langchain-community>=0.2.10",
  "fastapi",
]
```
Appreciated your help.

**Comment by JSilent** [comment]
Not reproducible after recreating docker image with new tag.
